//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUAHANG
    {
        public int MaCH { get; set; }
        public string TenCH { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> TrangThai { get; set; }
    }
}
