//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUAHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUAHANG()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public int MaTK { get; set; }
        public string TenCH { get; set; }
        public string DiaChi { get; set; }
        public string Logo { get; set; }
        public string MoTa { get; set; }
        public System.DateTime NgayThanhLap { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
