//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUAHANG_SANPHAM
    {
        public int MaCHSP { get; set; }
        public int MaTK_Store { get; set; }
        public int MaSP { get; set; }
        public decimal GiaBan { get; set; }
        public int SoLuongTon { get; set; }
        public bool TrangThai { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
    
        public virtual CUAHANG CUAHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
