//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIA
    {
        public int MaGia { get; set; }
        public int MaSP { get; set; }
        public decimal GiaCu { get; set; }
        public decimal GiaMoi { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string LyDoThayDoi { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
