//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIN_TUC
    {
        public int MaTin { get; set; }
        public int MaTK { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh { get; set; }
        public string Slug { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeywords { get; set; }
        public bool TrangThai { get; set; }
        public System.DateTime NgayDang { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
