//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VANCHUYEN
    {
        public int MaVC { get; set; }
        public int MaDH { get; set; }
        public string TenDonViVanChuyen { get; set; }
        public string MaVanDon { get; set; }
        public decimal PhiVanChuyen { get; set; }
        public decimal PhiCongKenh { get; set; }
        public decimal PhiLapRap { get; set; }
        public decimal TongPhiVanChuyen { get; set; }
        public Nullable<System.DateTime> NgayGiaoDuKien { get; set; }
        public Nullable<System.DateTime> NgayGiaoThucTe { get; set; }
        public string TrangThai { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
    }
}
